# Generated by Django 4.2.2 on 2023-06-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencegrade',
            name='grade',
            field=models.CharField(max_length=10),
        ),
    ]
