# Generated by Django 4.2.2 on 2023-06-19 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('score_check', '0002_alter_referencegrade_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference_Grade_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReferenceSubject', to='base.schoolinfo')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReferenceSubject', to='base.semesterinfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='referencesubject',
            name='grade',
        ),
        migrations.DeleteModel(
            name='ReferenceGrade',
        ),
        migrations.AlterField(
            model_name='referencesubsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReferenceSubject', to='score_check.reference_grade_subject'),
        ),
        migrations.DeleteModel(
            name='ReferenceSubject',
        ),
    ]
