# Generated by Django 4.2.2 on 2023-07-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_check', '0003_reference_grade_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_grade_subject',
            name='subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='referencesubsubject',
            name='subsubject',
            field=models.CharField(max_length=50),
        ),
    ]
